#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Windows .bat launchers as PURE ASCII + CRLF.

Why: On Chinese Windows (chcp 936 / GBK), cmd.exe parses .bat files
byte-by-byte using the ACTIVE CODEPAGE. A UTF-8 .bat with Chinese bytes
becomes garbled commands ("REG_SZ", "=%i )" ...). The only safe fix is to
keep .bat files 100% ASCII (ASCII is a strict subset of GBK, so it can
never garble under 936) and use CRLF line endings (LF-only makes multi-line
blocks like `if (...) else (...)` parse unreliably).

This script is the SINGLE SOURCE OF TRUTH for the two .bat files. Edit the
content here (UTF-8 Python string is fine), never hand-edit the .bat files
with a UTF-8 editor. Re-run to regenerate + self-validate.

Usage:
    python _gen_bat.py            # regenerate + validate
    python _gen_bat.py --check     # validate only (no write)
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


# --- Canonical .bat content (pure ASCII). Use \n; we convert to CRLF below. ---
# NEVER put non-ASCII (Chinese etc.) here. If you must add a comment, keep it
# English, or the .bat will garble on chcp 936.

RUN_HOST_BAT = r"""@echo off
setlocal
rem ============================================================
rem WinOCR-Html native host - standalone launcher (no browser).
rem Generated by _gen_bat.py - do not edit by hand.
rem
rem Hotkeys live in winocr_config.json: "hotkey" to capture, "quitHotkey" to quit.
rem
rem Interpreter: the path below was picked at GENERATION time as the one that
rem has tkinter + rapidocr + onnxruntime. Why it matters: those are optional
rem deps that usually live in only ONE of the installed pythons, while a bare
rem `where pythonw` picks whichever comes first in PATH - and a bare
rem interpreter has no tkinter at all, so the host dies at import with no
rem visible error at all (pythonw has nowhere to print).
rem If the path is gone we fall back to PATH, and winocr_host.py additionally
rem re-execs itself into a capable interpreter at startup (see pyenv.py),
rem so a wrong guess is survivable either way.
rem ============================================================
set "PYW=__PY__"
if not defined PYW goto fallback
if exist "%PYW%" goto launch
set "PYW="
:fallback
for /f "delims=" %%i in ('where pythonw 2^>nul') do ( if not defined PYW set "PYW=%%i" )
if not defined PYW for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PYW set "PYW=%%i" )
if not defined PYW (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\pythonw.exe" set "PYW=%LOCALAPPDATA%\Programs\Python\Python311\pythonw.exe"
)
if not defined PYW (
  echo [ERROR] python not found. Install Python 3 and add it to PATH.
  pause
  exit /b 1
)
:launch
start "" /b "%PYW%" "%~dp0winocr_host.py" --standalone
endlocal
"""

INSTALL_HOST_BAT = r"""@echo off
setlocal
rem ============================================================
rem Install WinOCR-Html native host (writes HKCU only - no admin needed)
rem
rem   1. locate python
rem   2. run setup_host.py  ->  writes winocr_launcher.bat + com.winocr.host.json
rem      (it auto-detects the extension id from the Edge/Chrome profiles,
rem       so there is nothing to edit by hand)
rem   3. register the host manifest for Edge and Chrome
rem
rem Safe to re-run at any time (e.g. after re-loading the extension).
rem Pass extra args through, e.g.:  install_host.bat --id <chrome-ext-id>
rem ============================================================

set "HOST_DIR=%~dp0"
set "SETUP=%HOST_DIR%setup_host.py"
set "JSON=%HOST_DIR%com.winocr.host.json"

rem ---- locate python ----
set "PY="
for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PY set "PY=%%i" )
if not defined PY (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PY=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
)
if not defined PY (
  echo [ERROR] python not found. Install Python 3 and add it to PATH.
  pause
  exit /b 1
)

rem ---- generate launcher + host manifest ----
"%PY%" "%SETUP%" %*
if errorlevel 1 (
  echo.
  echo [ERROR] setup_host.py failed - see the messages above.
  pause
  exit /b 1
)

rem ---- register for Edge and Chrome (HKCU) ----
reg add "HKCU\Software\Microsoft\Edge\NativeMessagingHosts\com.winocr.host" /ve /t REG_SZ /d "%JSON%" /f >nul
reg add "HKCU\Software\Google\Chrome\NativeMessagingHosts\com.winocr.host" /ve /t REG_SZ /d "%JSON%" /f >nul

echo.
echo [OK] Host manifest registered for Edge + Chrome:
echo      %JSON%
echo.
echo Next steps (inside the extension):
echo   1. edge://extensions          reload this extension
echo   2. extension options          tick "Connect native host", then Save
echo   3. click "Test host connection" -^> it should report: bridged
echo.
pause
"""


STOP_HOST_BAT = r"""@echo off
setlocal
rem ============================================================
rem Stop ALL WinOCR-Html native host processes (any instance, any mode).
rem Needed when a stale host keeps holding the global hotkey, which makes
rem the key you press get served by an OLD process (and its old bugs).
rem ============================================================

set "HOST_DIR=%~dp0"
set "PY="
for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PY set "PY=%%i" )
if not defined PY (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PY=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
)
if not defined PY (
  echo [ERROR] python not found. Install Python 3 and add it to PATH.
  pause
  exit /b 1
)

"%PY%" "%HOST_DIR%winocr_host.py" --stop

echo.
echo Done. Now start exactly ONE host:
echo   * desktop screenshots only   -^> run_host.bat
echo   * bridge to the extension    -^> do NOT start manually; the browser does it
echo.
pause
"""


INSTALL_DEPS_BAT = r"""@echo off
setlocal
rem ============================================================
rem WinOCR-Html - install the OPTIONAL local-OCR dependencies:
rem     numpy  Pillow  onnxruntime  rapidocr
rem
rem Without them the host still works: OCR falls back to SiliconFlow cloud
rem (needs sfKey). With them OCR runs offline with no key, ~1-2s per shot.
rem Generated by _gen_bat.py - do not edit by hand.
rem Extra args pass through, e.g.:  install_deps.bat --mirror
rem ============================================================
set "PY=__PYCON__"
if not defined PY goto fallback
if exist "%PY%" goto launch
set "PY="
:fallback
for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PY set "PY=%%i" )
if not defined PY (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PY=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
)
if not defined PY (
  echo [ERROR] python not found. Install Python 3 from python.org first
  echo         ^(keep "tcl/tk and IDLE" checked - the host GUI needs tkinter^)
  pause
  exit /b 1
)
:launch
echo Using: %PY%
"%PY%" "%~dp0install_deps.py" %*
echo.
pause
endlocal
"""


BATS = {
    "run_host.bat": RUN_HOST_BAT,
    "install_host.bat": INSTALL_HOST_BAT,
    "stop_host.bat": STOP_HOST_BAT,
    "install_deps.bat": INSTALL_DEPS_BAT,
}


def pick_host_python() -> str:
    """Pick the interpreter that has tkinter + the local-OCR stack.

    Returns a pythonw path (no console window), or "" when none qualifies.
    A wrong/empty result is survivable: winocr_host.py re-execs itself into a
    capable interpreter at startup (see pyenv.py), so this is only an
    optimisation that saves one re-exec.
    """
    try:
        if HERE not in sys.path:
            sys.path.insert(0, HERE)
        import pyenv
        exe, _miss, detail = pyenv.pick_best(required=("tkinter",) + tuple(pyenv.REQUIRED))
        if exe:
            target = pyenv.windowless_variant(exe) or exe
            print("[info] run_host.bat interpreter: %s  (%s)" % (target, detail))
            return target
        print("[warn] no interpreter with tkinter + local-OCR deps (%s)" % detail)
        print("[warn] run_host.bat will fall back to PATH; the host re-execs anyway.")
    except Exception as e:
        print("[warn] pyenv unavailable (%s: %s); run_host.bat falls back to PATH"
              % (type(e).__name__, e))
    return ""


def pick_install_python() -> str:
    """Pick any usable console interpreter for install_deps.bat.

    Deliberately does NOT require the deps to be present - installing them is
    this script's whole job. A console python (not pythonw) is required so the
    user can actually read pip's output.
    """
    try:
        if HERE not in sys.path:
            sys.path.insert(0, HERE)
        import pyenv
        exe = pyenv.install_target()
        if exe:
            print("[info] install_deps.bat interpreter: %s" % exe)
            return exe
    except Exception as e:
        print("[warn] pyenv unavailable (%s: %s)" % (type(e).__name__, e))
    return ""


def to_crlf_ascii(text: str) -> bytes:
    """Convert to CRLF line endings and encode as strict ASCII.

    Raises ValueError if any non-ASCII character is present.
    """
    # Normalize any existing \r\n or \r to \n first, then enforce \r\n.
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    # Encode strict ASCII: non-ASCII -> UnicodeEncodeError (surrogateescape off).
    data = normalized.encode("ascii")
    return data.replace(b"\n", b"\r\n")


def validate(path: str) -> None:
    with open(path, "rb") as f:
        raw = f.read()
    # 1) No high bytes (ASCII-only under GBK/936).
    bad = [i for i, b in enumerate(raw) if b >= 128]
    if bad:
        raise AssertionError(
            f"{path}: found {len(bad)} non-ASCII byte(s) at offsets {bad[:10]}... "
            f"-> will garble under chcp 936"
        )
    # 2) Contains CRLF (not bare LF).
    if b"\r\n" not in raw:
        raise AssertionError(f"{path}: missing CRLF line endings (found bare LF?)")
    # 3) No stray lone LF (every LF must be preceded by CR).
    if b"\n" in raw.replace(b"\r\n", b""):
        raise AssertionError(f"{path}: contains lone LF not part of CRLF")


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    injected = pick_host_python()
    install_py = pick_install_python()
    bats = dict(BATS)
    bats["run_host.bat"] = RUN_HOST_BAT.replace("__PY__", injected)
    bats["install_deps.bat"] = INSTALL_DEPS_BAT.replace("__PYCON__", install_py)
    for name, content in bats.items():
        out_path = os.path.join(HERE, name)
        try:
            data = to_crlf_ascii(content)
        except UnicodeEncodeError as e:
            print(f"[FAIL] {name}: contains non-ASCII -> {e}")
            return 1
        if not check_only:
            with open(out_path, "wb") as f:
                f.write(data)
        # Validate what is on disk (post-write, or pre-existing when --check).
        try:
            validate(out_path)
        except AssertionError as e:
            print(f"[FAIL] {name}: {e}")
            return 1
        verb = "validated" if check_only else "generated+validated"
        print(f"[OK]   {name}: {verb} ({len(data)} bytes, ASCII+CRLF)")
    print("\nAll .bat files are pure ASCII + CRLF; safe under chcp 936.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
