@echo off
setlocal
rem ============================================================
rem WinOCR-Html - install the OPTIONAL local-OCR dependencies:
rem     numpy  Pillow  onnxruntime  rapidocr
rem
rem Without them the host still works: OCR falls back to SiliconFlow cloud
rem (needs sfKey). With them OCR runs offline with no key, ~1-2s per shot.
rem Generated by _gen_bat.py - do not edit by hand.
rem Extra args pass through, e.g.:  install_deps.bat --mirror
rem ============================================================
set "PY=C:\Users\Administrator\AppData\Local\Python\pythoncore-3.14-64\python.exe"
if not defined PY goto fallback
if exist "%PY%" goto launch
set "PY="
:fallback
for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PY set "PY=%%i" )
if not defined PY (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PY=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
)
if not defined PY (
  echo [ERROR] python not found. Install Python 3 from python.org first
  echo         ^(keep "tcl/tk and IDLE" checked - the host GUI needs tkinter^)
  pause
  exit /b 1
)
:launch
echo Using: %PY%
"%PY%" "%~dp0install_deps.py" %*
echo.
pause
endlocal
