@echo off
setlocal
rem ============================================================
rem WinOCR-Html native host - standalone launcher (no browser).
rem Generated by _gen_bat.py - do not edit by hand.
rem
rem Hotkeys live in winocr_config.json: "hotkey" to capture, "quitHotkey" to quit.
rem
rem Interpreter: the path below was picked at GENERATION time as the one that
rem has tkinter + rapidocr + onnxruntime. Why it matters: those are optional
rem deps that usually live in only ONE of the installed pythons, while a bare
rem `where pythonw` picks whichever comes first in PATH - and a bare
rem interpreter has no tkinter at all, so the host dies at import with no
rem visible error at all (pythonw has nowhere to print).
rem If the path is gone we fall back to PATH, and winocr_host.py additionally
rem re-execs itself into a capable interpreter at startup (see pyenv.py),
rem so a wrong guess is survivable either way.
rem ============================================================
set "PYW=C:\Users\Administrator\AppData\Local\Python\pythoncore-3.14-64\pythonw.exe"
if not defined PYW goto fallback
if exist "%PYW%" goto launch
set "PYW="
:fallback
for /f "delims=" %%i in ('where pythonw 2^>nul') do ( if not defined PYW set "PYW=%%i" )
if not defined PYW for /f "delims=" %%i in ('where python 2^>nul') do ( if not defined PYW set "PYW=%%i" )
if not defined PYW (
  if exist "%LOCALAPPDATA%\Programs\Python\Python311\pythonw.exe" set "PYW=%LOCALAPPDATA%\Programs\Python\Python311\pythonw.exe"
)
if not defined PYW (
  echo [ERROR] python not found. Install Python 3 and add it to PATH.
  pause
  exit /b 1
)
:launch
start "" /b "%PYW%" "%~dp0winocr_host.py" --standalone
endlocal
