@echo off
rem WinOCR-Html native host launcher (auto-generated by setup_host.py)
rem Do not edit by hand - re-run: python setup_host.py
start "" /b "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\pythonw.exe" "D:\AI\WinOCR-Html0.3 - ??\native_host\winocr_host.py" %*
